### ISSUE TITLE
Relación LA_Agrupacion_Interesasdos - LA_Interesado

### ISSUE THREAD

**Issue by seralra96** [AgenciaImplementacion/LADM_COL#3]
Actualmente el modelo contempla una relación de 1 a muchos desde LA_Agrupacion_Interesados, pero pueden existir casos en los cuales hayan varias Agrupaciones de interesados donde un interesado natural o jurídico haga parte. Sería bueno contemplar una relación de muchos a muchos para que el modelo acepte esta particularidad.

Actualmente se encuentra así:

![image](https://user-images.githubusercontent.com/25961499/34217560-c6a50280-e579-11e7-9e8b-3d3297a366a3.png)

Podría estar así:

![image](https://user-images.githubusercontent.com/25961499/34217620-f00f84b0-e579-11e7-9a39-cb0150ab6919.png)

**Comment by mejiafabiandj** [comment]
ajustado https://github.com/AgenciaImplementacion/LADM_COL/commit/d785cf5e06507e98bf1f42ad7961b2dd3fe24174
